---
abstract: 'parse XML and specify what and how to keep/process for individual tags'
author:
  - 'Jan Krynicky <Jenda@CPAN.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Rules
provides:
  XML::Rules:
    file: lib/XML/Rules.pm
    version: 1.10
requires:
  XML::Parser: 2.00
  XML::Parser::Expat: 2.00
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
version: 1.10
